name: Setup Python with uv
description: Install uv and set up Python

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "latest"

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
